config/routes.rb
PostitTemplate::Application.routes.draw do

	root to: 'posts#index'




	get '/register', to: 'users#new' # change user#new to register
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  #get '/profile', to: 'users#show'
  get '/profile', controller: :users, to: :show

  
  resources :posts, except: [:destroy] do
    member do
      post :vote 
    end
  	resources :comments, only: [:create]
  end

  resources :comments do 
    member do
      post :vote
    end
  end

  resources :categories, only: [:create, :new, :show]
  resources :tests
  resources :users

  namespace :admin do 
    resources :articles, :tests
  end








end
# $rake route
#this can see the created route

#or url: localhost:3000/rails/info/routes

app/models/category.rb
class Category < ActiveRecord::Base
	include Sluggable
  has_many :post_categories
  has_many :posts, through: :post_categories
  sluggable_column(:name)
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include Voteable #lib/voteable.rb

  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Sluggable
  include Voteable

  has_many :comments
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User' # to make association more expressive, need to add the foreign_key and class_name
  # $post.creator <--OK
  # $post.user <--NO OK anymore 
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :url, presence: true

  sluggable_column(:title)





end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}
  validates :phone_number, presence: true
  validates :email, presence: true

  has_secure_password validations: false

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :voter, scope: [:voteable_id, :voteable_type]
  #same as above
  #validates :voter, uniqueness: {scope: [:voteable_id, :voteable_type], message: 'You can not vote twice'}
  #or
  #validates_uniqueness_of :voter, scope: :voteable 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   helper_method :current_user, :logged_in?, :can_vote?, :admin? #定義哪些method可以同時當作helper_method給view使用

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def can_vote?(post)
    if logged_in?
      all_voter = post.votes.map{|vote| vote.user_id }
      !all_voter.include?(current_user.id)
    else 
      false #not logged_in
    end
  end

  def require_user
   access_denied if !logged_in?
  end

  def admin?
    true if current_user.username == 'admin'
  end

  def access_denied
    flash[:error] = 'You can not do this'
    redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      flash[:notice] = 'Category is created'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show 
    @category = Category.find_by(slug: params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_user

  def create

    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = Post.find_by(slug: params[:post_id])
    @comment.user = current_user
    @post = @comment.post

    if @comment.save
      flash[:notice] = 'Comment is created'
      redirect_to post_path(@comment.post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    Vote.create(voteable: @comment, voter: current_user, vote: params[:vote])
    respond_to do |format|
      format.html {redirect_to :back}
      format.js 
    end
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #require 'pry'

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]
  # Use case:
  #   1. setup instance variable for action
  #   2. redirect base on some condition. EX: authutication.
  
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json do 
        render json: @post
      end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(strong_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Your post is create successfully'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(strong_params)
      flash[:notice] = 'Your post is updated!'
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def vote # this action is been routed in route.rb using member syntex
    Vote.create(voteable: @post, voter: current_user, vote: params[:vote]) #voteable is polymorphic convention
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def set_post 
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.username == 'admin')
  end

  private

  def strong_params
    params.require(:post).permit(:title, :url, :description, :user_id) # permit! will permit all attributes
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      # HAPPY PATH
      session[:user_id] = user.id
      flash[:notice] = 'Login successfully'
      redirect_to root_path
    else
      flash[:error] = 'Your username or password is wrong'
      render 'sessions/new' #In the video is using redirect_to, why?
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You are logged out, goodbye'
    redirect_to root_path
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def show
  
  end

  def index

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_same_user, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(strong_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Successfully registered'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    binding.pry
    @user = User.find(session[:user_id])
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(strong_params)
      flash[:notice] = 'You have successfully update'
      redirect_to user_path(@user)
    else
      params[:show_info] = 'edit'
      render 'users/show'
    end

  end

  def require_same_user
    if current_user.id != params[:id].to_i
      flash[:error] = 'You can not edit this profile' 
      redirect_to user_path(current_user)
    end
  end

  private

  def strong_params
    params.require(:user).permit(:username, :password, :phone_number, :email, :time_zone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def fixed_url(url)
    url.starts_with?('http://') ? url : "http://#{url}" #單括號不行！！
  end

  def time_format(date_time)
  	if logged_in? && !current_user.time_zone.blank?
  		date_time = date_time.in_time_zone(current_user.time_zone)
  	end
    date_time.strftime("%b/%d/%Y %I:%M%p %Z")
  end
end

app/views/categories/_category.html.erb
<span class = 'badge'><%= link_to category.name, category_path(category) %></span>

<!-- this is a collection partial recored in Mod1-5 -->

app/views/categories/new.html.erb
<%= render 'shared/error', obj: @category %>

<h2>Create New Cagetory</h2>
<hr>

<%= form_for @category do |f| %>
  <div class = 'control_group'>
    <%= f.label :name, 'Category Name' %>
    <%= f.text_field :name %>
  </div>
  <br>
  <%= f.submit 'Create New Category', class: 'btn btn-primary' %>
<% end %>
 

app/views/categories/show.html.erb
<%= render 'shared/content_title', title: ' &raquo; '.html_safe + @category.name %>
<!-- html_safe can transfer string back to HTML code -->
<% @category.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>

app/views/comments/vote.js.erb
$('#vote_<%= @comment.id%>_comment').html('<%= @comment.count_vote %> liked')
$('#vote_up_for_<%= @comment.id%>_comment').html('')
$('#vote_down_for_<%= @comment.id%>_comment').html('')

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="success">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <div class = 'row-fluid'>  
    
    <div class = 'span4 offset1 nav_item'>

      <ul class="nav">
        <li>
          <%= link_to "Postit!", root_path, :class => 'brand' %>
        </li>
      </ul>

      <% if logged_in? %>
        <%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>
      <% end %>

      <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
          Category
          <i class="caret"></i>
          <!-- <span class="caret"></span> --> <!-- this also works like the line above -->
        </button>
      <!--   DROPDOWN  menu-->
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <% Category.all.each do |category| %>
            <li role="presentation">
              <%= link_to category.name, category_path(category) %>
            </li>
          <% end %>
          <% if logged_in? %>
          <li class = 'divider'></li>
          <li>      
            <%= link_to(new_category_path) do %>
              <i class = 'icon-plus'></i>
              New Category
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>

    </div>

    <div class = 'span6 nav_item'>
      <!--   DROPDOWN  button-->

      <!-- User authentication -->
      <div class = 'pull-right'>
        <% if logged_in? %> <!-- logged_in -->
          <div class = 'brand'> Hi, <%= current_user.username %> </div>
          <%= link_to 'Profile', profile_path, class: 'btn btn-success'%>
          <%= link_to 'Logout', logout_path, class: 'btn btn-warning' %>
        <% else %>
          <%= link_to 'Register', register_path, class: 'btn btn-success' %>
          <%= link_to 'Login', login_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>

  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class = 'container'>

          <%= render 'layouts/messages' %>
          <%= yield %>

      </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_comment.html.erb
<% if comments.any? %>
<hr>
<% end %>
<% comments.each do |comment|%>
  <div class = 'row'>
    <div class = 'span4 well'>

      <div class= 'pull-right'>
        <% if can_vote?(comment) %>
          <%= link_to vote_comment_path(comment, vote: true), method: 'post', remote: true do %>
            <span id = 'vote_up_for_<%= comment.id%>_comment'>
              <i class = 'icon-thumbs-up'></i>
            </span>
          <% end %>
          <%= link_to vote_comment_path(comment, vote: false), method: 'post', remote: true do %>
            <span id = 'vote_down_for_<%= comment.id%>_comment'>
              <i class = 'icon-thumbs-down'></i>
            </span>
          <% end %>
        <% end %>
          <span id = 'vote_<%= comment.id%>_comment' class = "label label-<%= comment.count_vote >= 0 ? "info" : "warning" %>">
            <%= comment.count_vote %> liked
          </span>
      </div>

      <%= comment.body %>
      <br>
      <br>
      <span class = 'quiet'>by:</span> 
      <strong>
        <%= link_to comment.user.username, user_path(comment.user, show_info: 'post') %>
      </strong>
      <br>
      <% if params[:show_info] == 'comment'%>
      <span class = 'quiet'>Comment on:</span> 
      <strong>
        <%= link_to comment.post.title, post_path(comment.post) %>
      </strong>
      <% end %>
   </div>

  </div>
<% end %>

app/views/posts/_form.html.erb
<%= render 'shared/error', obj: @post %>

<%= form_for @post do |f|%> <!-- have = sign here --> 

  <div class = 'control_group'>  
    <%= f.label :title %> <!-- here  can only be attribute or virtual attribute, cant't be anything!! -->
    <%= f.text_field :title %>
  </div>
  <div class = 'control_group'>  
    <%= f.label :url %> <!-- here  can only be attribute or virtual attribute, cant't be anything!! -->
    <%= f.text_field :url %>
  </div>
  <div class = 'control_group'>  
    <%= f.label :description %> <!-- here  can only be attribute or virtual attribute, cant't be anything!! -->
    <%= f.text_area :description, rows: 5 %>
  </div>
  <div class = 'control_group'>  
    <%= f.label 'Categories' %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
    <% end %>
  </div>
  </br>
  <%= f.submit create_or_update_button, class: 'btn btn-primary'%> <!-- here is class:, not class = --> 
<% end %>   


<!-- TEST AREA 
<%= form_tag('/tests', method: 'get') do %>
  <%= label_tag(:q, 'Search for:') %>
  <%= text_field_tag(:q) %>
  <br>
  <div class = 'checkbox inline'>
  <%= check_box_tag(:own_dog) %>
  <%= label_tag(:own_dog, 'I own a dog') %>
  </div>
  <br>
  <%= submit_tag('Search', class: 'btn btn-primary')  %>

<% end %>
-->

app/views/posts/_post.html.erb
<!-- passing attr: post -->
<div class = 'row'>
    <div class = "span1 well text-center">

      <% if can_vote?(post) %>
        <div id = 'post_<%= post.slug %>_voted_up'> <!-- for Ajox -->
          <%= link_to vote_post_path(post, vote: true), method: 'post',remote: true do %>
            <i class = 'icon-arrow-up'></i>
          <% end %>
        </div>
      <% end %>
      <span id = 'vote_on_<%= post.slug %>_post'><!-- for Ajox -->
        <%= post.count_vote %></span> liked
      <br>

      <% if can_vote?(post) %>
      <div id = 'post_<%= post.slug %>_voted_down'><!-- for Ajox -->  
         <%= link_to vote_post_path(post, vote: false), method: 'post',remote: true do %>
           <i class = 'icon-arrow-down'></i>
         <% end %>
      </div>
      <% end %>

    </div>

    <div class = "span8 well">

      <%= render post.categories %>

      <h4> <%= link_to post.title, fixed_url(post.url) %> </h4>
      <p> <%= post.description %> </p>
      <p>
        <span class = 'quiet' >posted by</span> <strong> <%= post.creator.username %></strong>
        <small>at <%= time_format(post.created_at) %> </small>
      </p>

      <small>
        <span>
          <%= link_to "#{post.comments.size} comments", post_path(post.to_param)%>
        </span>
      </small>

    </div>
</div>

app/views/posts/edit.html.erb
<h2>Update this form</h2>

<%= render 'form', create_or_update_button: 'Update Post' %>

app/views/posts/index.html.erb
	<div class = 'row'>
		<%= render 'shared/content_title', title: nil %>
	</div>

	<% @posts.each do |post| %>
  	<%= render 'post', post: post %>
	<% end %>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render 'form', create_or_update_button: 'Create Post'%>

app/views/posts/show.html.erb
<!-- Edit link -->
<% if logged_in? and (@post.creator == current_user || current_user.username == 'admin') %>
<div class = 'pull-right'>
  [<%= link_to 'Edit this Post', edit_post_path(@post)%>]
</div>
<% end %>

<p>
  <%= render @post.categories %> <!-- Collection partial -->
</p>

<%= render 'shared/content_title', title: ' &raquo; '.html_safe + @post.title %> <!-- standard partial syntax, this will render the shared/_content_title  -->

<p>
  <%= @post.description %>
</p>

<!-- Show comments -->
<%= render 'posts/comment', comments: @post.comments %>
<!-- Create comment -->
<%= render 'shared/error', obj: @comment %>
<% if logged_in? %>
  <hr>
  <%= form_for [@post, @comment] do |f| %> <!-- remember the [ ], and @post is the exsiting OBJ which the @comment is the new OBJ -->
    <%= f.label :body, 'Create a comment' %>
    <%= f.text_area :body %>
    <br>
    <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<hr>

app/views/posts/vote.js.erb
$('#vote_on_<%= @post.slug %>_post').html('<%= @post.count_vote %>')
$('#post_<%= @post.slug %>_voted_up').html('') // Hide arrow when voted
$('#post_<%= @post.slug %>_voted_down').html('') // Hide arrow when voted

app/views/shared/_content_title.html.erb
<p class = 'lead'>
<% all_posts = (link_to 'All posts', posts_path) %> 
<h2> <%= all_posts + title %> </h2><!-- title is a variable can be rendered -->
  <hr/>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class = 'alert alert-error'>
	  <h3> There are some errors:</h3>
	  <% obj.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<!-- Error message -->

<%= render 'shared/error', obj: @user %>

<!-- Form -->
<div class = 'span8 well'>
  <%= form_for @user do |f| %>

    <div class = 'control_group'> 
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <% if show_password == true %>
      <div class = 'control_group'> 
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
    <% end %>
    <div class = 'control_group'> 
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>

    <div class = 'control_group'> 
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class = 'control_group'> 
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {include_black: true} %> <!-- ActiveSupport::TimeZone have support lots of ways to customize the display of the list -->
    </div>

    <!-- gender -->

    <br>
    
    <%= f.submit current_user ? "Update Profile" : "Register Now" , class: 'btn btn-primary'%>
  <% end %> 

</div>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render 'form', show_password: false %>

app/views/users/new.html.erb
<h2>Register new account</h2>

<%= render 'form', show_password: true %>

app/views/users/show.html.erb
<h2>Profile</h2>

<div class= 'well control-group'>
  <dl class = 'dl-horizontal'>
    <dt>User Name:</dt>
    <dd><%= User.find(@user.id).username %></dd>
    <br>
    <dt>Phone Number:</dt>
    <dd><%= User.find(@user.id).phone_number %></dd>
    <br>
    <dt>E-Mail:</dt>
    <dd><%= User.find(@user.id).email %></dd>
  </dl>
</div>
<h3><%= User.find(@user.id).username%>'s Activity</h3>
</br>
<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:show_info] == 'post'%>">
    <%= link_to 'Posts', user_path(@user, show_info: 'post') %>
  </li>
  <li class="<%= 'active' if params[:show_info] == 'comment'%>">
    <%= link_to 'Comments', user_path(@user, show_info: 'comment') %>
  </li>
  <li class="<%= 'active' if params[:show_info] == 'edit'%> pull-right">
    <%= link_to 'Edit Profile', user_path(@user, show_info: 'edit') %>
  </li>
</ul>

<%if params[:show_info] == 'post' %>

  <% @user.posts.each do |post| %>
    <%= render '/posts/post', post: post %>
  <% end %>

<% elsif params[:show_info] == 'comment' %>

  <%= render '/posts/comment', comments: @user.comments %>

<% elsif params[:show_info] == 'edit' %>
  <h2>Edit Profile</h2>
  <%= render 'form', show_password: false %>

<% end %>